### PR TITLE
Create rs.scrbl

### PR DESCRIPTION
**Pull request by spdegabrielle**
sorry about the changelog. It's not as good as it could be. I've asked how best to handle nested lists with code on the racket slack.

### CODE REVIEW

**Comment by spdegabrielle** [comment]
to enable it change `(define scribblings '(("rs.scrbl" (multi-page))))` in info.rkt to `(define scribblings '(("scribblings/rs.scrbl" (multi-page))))`

**Comment by mcdejonge** [comment]
Ouch ... you won't believe what I started typing up this afternoon:

https://github.com/mcdejonge/rs/blob/master/rs.scrbl

That said: is it a convention to have these documents in a directory scribblings? If so, I'll move my effort to where it belongs.

**Comment by spdegabrielle** [comment]
My apologies - I didn't realise.

> That said: is it a convention to have these documents in a directory scribblings? 

yes it is a convention but not required. If you do `raco pkg new <pkgname>` is creates the scribblings folder amongst other things.

**Comment by spdegabrielle** [comment]
We didn't duplicate work. I just transformed your readme into scribble, you documented the functions provided.

**Comment by spdegabrielle** [comment]
Please use or reject as you see fit.

**Comment by mcdejonge** [comment]
Thanks for your effort. I already copied over some settings you provided and I'll merge the two files.

**Pull request merged**
